### ISSUE TITLE
Add ability to monitor commit comments

### ISSUE THREAD

**Issue by patcon** [eteled/issues#3]
Forked from https://github.com/isaacs/github/issues/38#issuecomment-29835910 :)

cc: @captn3m0 @isaacs

**Comment by captn3m0** [comment]
I've added this functionality to the bot, but unfortunately, due to a bug in the GitHub API, this is not usable at the moment. You can test the functionality (working) [on this commit](https://github.com/eteled/issues/commit/dac4cf4ed727897157bb7152f5a096f9c3402fd5#commitcomment-4779956).

The bug in the API shows up when a repo-collaborator (not the repo owner) tries to delete a commit-comment. I've sent in a mail to GitHub support regarding the bug. For instance, if you try commenting on [this commit](https://github.com/captn3m0/github-image-post/commit/c811a12241a4f9f2e606c746964ad218db594155), eteled tries to delete the comment but is unsuccessful because the DELETE method on the API returns a 404(not found) instead of a 204(No content).

This should start working automatically as soon as GitHub fixes the bug on their side.

**Comment by captn3m0** [comment]
Received confirmation on the bug from GitHub:

> Hi Abhay,
> 
> Thanks for pointing this out! This indeed looks like a bug -- I've opened an issue to let our developers know about it. If they have any questions, we'll hit you up for more information.
> 
> Cheers,
> Ivan

**Comment by captn3m0** [comment]
Ivan just mailed me and the bug is now fixed on GitHub's side. Just tested this now and it works.
